source :gemcutter

# Gems required by the Picky client.
#
gem 'picky-client'
gem 'i18n'
gem 'activesupport', :require => 'active_support/core_ext'
gem 'sinatra'
gem 'haml'
gem 'yajl-ruby', :platforms => :ruby
gem 'json-jruby', :platforms => :jruby

group :development do
  gem 'sinatra-reloader'
end
